steps:
- task: MicroBuildSigningPlugin@1
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: Install MicroBuild Signing Plugin
  condition: eq(variables['System.PullRequest.IsFork'], 'false')
